### ISSUE TITLE
HL backend throws internal error

### ISSUE THREAD

**Issue by ghost** [Beeblerox/Heaps-Spine#1]
I am using Ubuntu 18.10, hl 1.9.0, haxe 4.0.0-rc.2+77068e1. When trying to compile and run the HL version using the SDL library I get an error.

`JIT ERROR 9 (jit.c line 3296)`

Should I open an issue in the HashLink repository or did this error happen to you before? Maybe you have some experience with that kind of error while developing the library.

Thanks.

**Comment by ghost** [comment]
Ok, found your discussions in the HashLink repository. I am not sure about the current status, though. So as far as I understand the problem is known, will be fixed sometime in the future by the HashLink team, and in the meantime you did a workaround.

So the solution is to use the latest Github version of `spine-hx` and `Heaps-Spine` and then everything should work. Is this right? If so I will try out tomorrow. (It's already very late over here.)

Thanks.

**Comment by Beeblerox** [comment]
yes, i think that github version of spine-hx should help
will wait for your results

**Comment by ghost** [comment]
Used the latest version of spine-hx(3.6) from the GitHub repository and it runs fine.

Thank you!

Just as a note to myself:
```
git clone https://github.com/jeremyfa/spine-hx.git
sudo haxelib dev spine-hx spine-hx
haxelib list
```
or use instead of cloning with the `git` command:
```
sudo haxelib git spine-hx git@github.com:jeremyfa/spine-hx.git
```
My haxelib directory is in `/usr/lib/haxe/lib/`. Therefore `sudo` is necessary.
